##
# Travis YAML
##

language : ruby
sudo     : true
cache    : bundler

before_script :
  - echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - npm i
  - npm i critical svgo -g
  - bundle install
  - gem install middleman

rvm :
  - 2.4.2

os :
  - linux

matrix :
  fast_finish    : true
  allow_failures :
    - rvm : ruby-head

script : bundle exec middleman build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

env :
  global :
    - TEST=true
    - CODECLIMATE_REPO_TOKEN=318bfc563d297acab6ff3f1d35b76373ded071e7ca8abe448c9b5d4866822870
